### ISSUE TITLE
Register does not validate email and password strength

### ISSUE THREAD

**Issue by tolgaozgun** [LinguistAI/user#8]
Both the email and the password is not validated at register.

Frontend uses the following regex for email: /\b[\w\\.+-]+@[\w\\.-]+\.\w{2,4}\b/

Password requirements are also defined as:

  const passwordRequirements: Requirement[] = [
    {
      re: /^.{8,}$/,
      label: "Must be at least 8 characters long.",
    },
    {
      re: /[A-Z]/,
      label: "Must contain at least 1 uppercase letter.",
    },
    {
      re: /[0-9]/,
      label: "Must contain at least 1 number.",
    },
    {
      re: /[^A-Za-z0-9]/,
      label: "Must contain at least 1 special character.",
    },
  ];

**Comment by elif-krvan** [comment]
This issue is resolved in the previous sprint.
